CREATE TABLE JDBC_DIMAS.dbo.Buku
(
    ID int PRIMARY KEY NOT NULL IDENTITY,
    JUDUL_BUKU varchar(60) NOT NULL,
    NAMA_PENGARANG varchar(125),
    PENERBIT_ID int,
    TAHUN_TERBIT int,
    TANGGAL_PUBLISH date NOT NULL,
    ISBN varchar(64) NOT NULL,
    TERSEDIA bit,
    CREATED_DATE datetime NOT NULL,
    LAST_UPDATE_DATE datetime,
    CREATED_BY varchar(10),
    UPDATED_BY varchar(10)
)
CREATE UNIQUE INDEX PK__Buku__3214EC2783CEDE05 ON JDBC_DIMAS.dbo.Buku (ID);